/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginPageRouteImport } from './routes/login-page.route'
import { Route as BalanceIndexImport } from './routes/balance/index'

// Create/Update Routes

const LoginPageRouteRoute = LoginPageRouteImport.update({
  id: '/login-page',
  path: '/login-page',
  getParentRoute: () => rootRoute,
} as any)

const BalanceIndexRoute = BalanceIndexImport.update({
  id: '/balance/',
  path: '/balance/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login-page': {
      id: '/login-page'
      path: '/login-page'
      fullPath: '/login-page'
      preLoaderRoute: typeof LoginPageRouteImport
      parentRoute: typeof rootRoute
    }
    '/balance/': {
      id: '/balance/'
      path: '/balance'
      fullPath: '/balance'
      preLoaderRoute: typeof BalanceIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/login-page': typeof LoginPageRouteRoute
  '/balance': typeof BalanceIndexRoute
}

export interface FileRoutesByTo {
  '/login-page': typeof LoginPageRouteRoute
  '/balance': typeof BalanceIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/login-page': typeof LoginPageRouteRoute
  '/balance/': typeof BalanceIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login-page' | '/balance'
  fileRoutesByTo: FileRoutesByTo
  to: '/login-page' | '/balance'
  id: '__root__' | '/login-page' | '/balance/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LoginPageRouteRoute: typeof LoginPageRouteRoute
  BalanceIndexRoute: typeof BalanceIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  LoginPageRouteRoute: LoginPageRouteRoute,
  BalanceIndexRoute: BalanceIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/login-page",
        "/balance/"
      ]
    },
    "/login-page": {
      "filePath": "login-page.route.tsx"
    },
    "/balance/": {
      "filePath": "balance/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
